services:
  app:
    build:
      context: .
    restart: always
    hostname: medicus
    environment:
      - ENV NODE_ENV=Preprod
      - ENV ASPNETCORE_ENVIRONMENT=Preprod
networks:
  default:
    name: application