services:
  sql:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "postgrespw"
  auth:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    hostname: auth
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "1P%cuS9tMIk0"
    command: ["start-dev"]
  app:
    build:
      context: .
    restart: always
    hostname: medicus
    depends_on:
      - sql
      - auth
networks:
  default:
    name: application