services:
  app:
    build:
      context: .
    restart: always
    hostname: medicus
    environment:
      - NODE_ENV=Preprod
      - TEST_NODE_ENV=Preprod
      - ASPNETCORE_ENVIRONMENT=Preprod
networks:
  default:
    name: application