services:
  app:
    build:
      context: .
    restart: always
    hostname: medicus
    environment:
      - ENV NODE_ENV=Production
      - ENV ASPNETCORE_ENVIRONMENT=Production
networks:
  default:
    name: application