services:
  migration:
    build:
      context: .
    entrypoint: "dotnet ef database drop -f"
  drop:
    build:
      context: .
    entrypoint: "dotnet ef database update"
networks:
  default:
    name: application